In [1]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import matplotlib.pyplot as plt
import seaborn as sns
matches = pd.read_csv('matches.csv')
deliveries = pd.read_csv('deliveries.csv')

In [5]:
matches.head(2)

,ID,season,city,date,team1,team2,toss_winner,toss_decision,result,dl_applied,...,win_by_wickets,player_of_match,venue,umpire1,umpire2,umpire3,toss_imp,team1team2,teamA,teamB
0,1,2017,Hyderabad,4/5/2017,Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,...,0,Yuvraj Singh,"Rajiv Gandhi International Stadium, Uppal",AY Dandekar,NJ Llong,NaN,NO,"[Royal Challengers Bangalore, Sunrisers Hydera...",Royal Challengers Bangalore,Sunrisers Hyderabad
1,2,2017,Pune,4/6/2017,Mumbai Indians,Rising Pune Supergiants,Rising Pune Supergiants,field,normal,0,...,7,SPD Smith,Maharashtra Cricket Association Stadium,A Nand Kishore,S Ravi,NaN,YES,"[Mumbai Indians, Rising Pune Supergiants]",Mumbai Indians,Rising Pune Supergiants

In [7]:
deliveries.head(2)

,ID,inning,batting_team,bowling_team,over,ball,batsman,non_striker,bowler,is_super_over,...,bye_runs,legbye_runs,noball_runs,penalty_runs,batsman_runs,extra_runs,total_runs,player_dismissed,dismissal_kind,fielder
0,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,1,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
1,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,2,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN

In [2]:
matches.loc[(matches.team1=='Rising Pune Supergiant') ,'team1'] = 'Rising Pune Supergiants'
matches.loc[(matches.team2=='Rising Pune Supergiant') ,'team2'] = 'Rising Pune Supergiants'
matches.loc[(matches.toss_winner=='Rising Pune Supergiant') ,'toss_winner'] = 'Rising Pune Supergiants'
matches.loc[(matches.winner=='Rising Pune Supergiant') ,'winner'] = 'Rising Pune Supergiants'
matches.loc[(matches.venue=='Punjab Cricket Association IS Bindra Stadium, Mohali') ,'venue'] = 'Punjab Cricket Association Stadium, Mohali'

matches['toss_imp'] = np.where(matches['toss_winner']== matches['winner'], 'YES', 'NO')

In [3]:
matches['team1team2'] = list(zip(matches.team1, matches.team2))
def sortvalue(x):
    return sorted(x)

matches['team1team2']=matches.apply(lambda x : sortvalue(x['team1team2']) , axis = 1  ) 
matches[['teamA', 'teamB']] = pd.DataFrame(matches['team1team2'].tolist(), index=matches.index)

In [8]:
Match_deliveries = pd.merge(deliveries, matches, how='left', left_on='ID', right_on='ID' )
Match_deliveries.head(2)

,ID,inning,batting_team,bowling_team,over,ball,batsman,non_striker,bowler,is_super_over,...,win_by_wickets,player_of_match,venue,umpire1,umpire2,umpire3,toss_imp,team1team2,teamA,teamB
0,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,1,DA Warner,S Dhawan,TS Mills,0,...,0,Yuvraj Singh,"Rajiv Gandhi International Stadium, Uppal",AY Dandekar,NJ Llong,NaN,NO,"[Royal Challengers Bangalore, Sunrisers Hydera...",Royal Challengers Bangalore,Sunrisers Hyderabad
1,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,2,DA Warner,S Dhawan,TS Mills,0,...,0,Yuvraj Singh,"Rajiv Gandhi International Stadium, Uppal",AY Dandekar,NJ Llong,NaN,NO,"[Royal Challengers Bangalore, Sunrisers Hydera...",Royal Challengers Bangalore,Sunrisers Hyderabad

In [9]:
deliveries[(deliveries['dismissal_kind'].notnull() )].groupby(['bowler','dismissal_kind']).size()

bowler           dismissal_kind
A Ashish Reddy   bowled                6
                 caught                8
                 caught and bowled     1
                 lbw                   3
                 run out               1
A Chandila       caught                4
                 caught and bowled     5
                 stumped               2
A Choudhary      caught                5
A Flintoff       caught                1
                 caught and bowled     1
A Kumble         bowled                8
                 caught               24
                 caught and bowled     1
                 lbw                   4
                 run out               4
                 stumped               8
A Mishra         bowled               21
                 caught               74
                 caught and bowled     3
                 lbw                  13
                 run out               8
                 stumped              23
A Mithun         bowled                2
                 caught                5
                 run out               1
A Nehra          bowled               23
                 caught               76
                 caught and bowled     2
                 lbw                   5
                                      ..
Y Venugopal Rao  caught                4
                 lbw                   1
                 run out               1
YA Abdulla       bowled                4
                 caught               10
                 lbw                   1
YK Pathan        bowled                9
                 caught               21
                 caught and bowled     2
                 lbw                   5
                 run out               4
                 stumped               4
YS Chahal        bowled                9
                 caught               49
                 caught and bowled     1
                 lbw                   3
                 run out               2
                 stumped               8
Yuvraj Singh     bowled                9
                 caught               19
                 caught and bowled     2
                 lbw                   2
                 run out               3
                 stumped               4
Z Khan           bowled               22
                 caught               70
                 caught and bowled     1
                 lbw                   9
                 retired hurt          1
                 run out              16
Length: 1065, dtype: int64